### ISSUE TITLE
[macOS Big Sur] build error

### ISSUE THREAD

**Issue by dmazzella** [0lru/p3ui#2]
Hi @0lru ,
i have tried to build on macOS but without success.

```
➜  p3ui (main) ✗ g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
➜  p3ui (main) 
```

build with Python 3.9.6:

`➜  p3ui (main) ✗ python setup.py build
`

i have this errors:

```
/Users/damianomazzella/projects/p3ui/cpp/p3_parser/source/p3/Parser.cpp:142:33: error: template specialization requires 'template<>'
    pos Rule<Percentage, void>::parse(pos begin, Percentage& percentage)
        ~~~~~~~~~~~~~~~~~~~~~~  ^
    template<> 
/Users/damianomazzella/projects/p3ui/cpp/p3_parser/source/p3/Parser.cpp:155:28: error: template specialization requires 'template<>'
    pos Rule<float, void>::parse(pos begin, float& value)
        ~~~~~~~~~~~~~~~~~  ^
    template<> 
/Users/damianomazzella/projects/p3ui/cpp/p3_parser/source/p3/Parser.cpp:166:39: error: template specialization requires 'template<>'
    pos Rule<LengthPercentage, void>::parse(pos begin, LengthPercentage& length_percentrage)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
    template<> 
/Users/damianomazzella/projects/p3ui/cpp/p3_parser/source/p3/Parser.cpp:183:28: error: template specialization requires 'template<>'
    pos Rule<Color, void>::parse(pos begin, Color& color)
        ~~~~~~~~~~~~~~~~~  ^
    template<> 
/Users/damianomazzella/projects/p3ui/cpp/p3_parser/source/p3/Parser.cpp:194:47: error: template specialization requires 'template<>'
    pos Rule<OptionalLengthPercentage, void>::parse(pos begin, OptionalLengthPercentage& olp)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
    template<> 
/Users/damianomazzella/projects/p3ui/cpp/p3_parser/source/p3/Parser.cpp:211:35: error: template specialization requires 'template<>'
    pos Rule<LayoutLength, void>::parse(pos begin, LayoutLength& fd)
        ~~~~~~~~~~~~~~~~~~~~~~~~  ^
    template<> 
```

### add `template<>  pos Rule<`... solve problem.

```
/Users/damianomazzella/projects/p3ui/cpp/p3/source/p3/StyleBlock.h:109:32: error: implicit instantiation of undefined template 'std::__1::vector<p3::StyleBlock::Observer *>'
        std::vector<Observer*> _observer;
                               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
```

### add  `#include <vector>` solve problem.

```
/Users/damianomazzella/projects/p3ui/cpp/p3/source/p3/log.h:26:10: fatal error: 'source_location' file not found
#include <source_location>
         ^~~~~~~~~~~~~~~~~
```

but with this i can solve, I have tried experimental include but no headers found.

Any hint?

Thanks,
D.

**Comment by 0lru** [comment]
Found https://github.com/paweldac/source_location, but this seems to support Linux only.
I will try to build macOS later this week. Maybe it also requires a "metal" implementation.

**Comment by dmazzella** [comment]
> Found https://github.com/paweldac/source_location, but this seems to support Linux only.
> I will try to build macOS later this week. Maybe it also requires a "metal" implementation.

Hi @0lru, progress on macOS support?

**Comment by 0lru** [comment]
Sorry for the late response. I was first a bit short in time and then changed my mind a bit.
I think it's more important to get this running:
* https://github.com/0lru/p3ui/tree/asyncio_api
This will change the API a bit (the properties getters will return futures, the setters will stay the same). Once this is stable and if it's more performant,
I'll try out Vulkan on Linux, I think.

Since I do not own a Mac, it's questionable if I ever will do this. But on the other hand, all this (see above) will take some time and maybe we can compile it then with [Molton](https://moltengl.com/moltenvk/) out of the box. But, to be honest, I've little experience with mac. Is Molton a "nogo"? :-)

**Comment by 0lru** [comment]
Note: Reverted "back" to C++17 but added Skia in C++. I think "Metal" is not required yet, since OpenGL is only deprecated but still available. Could work, but now needs some additional rules/work for building skia inside the p3ui_skia-repo first.
